# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161008_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='allzuser',
            name='username',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
